#!/usr/bin/env bash

apm install atom-beautify
apm install atom-typescript
apm install auto-detect-indentation
apm install autoclose-html
apm install autocomplete-modules
apm install autocomplete-paths
apm install color-picker
apm install emmet
apm install ex-mode
apm install file-icons
apm install git-blame
apm install git-time-machine
apm install highlight-selected
apm install language-babel
apm install linter
apm install linter-eslint
apm install linter-flake8
apm install merge-conflicts
apm install minimap
apm install minimap-linter
apm install nuclide
apm install pigments
apm install react
apm install sort-lines
apm install synced-sidebar
apm install tool-bar
apm install vim-mode
